### ISSUE TITLE
Does not work with ESP32-PICO-D4

### ISSUE THREAD

**Issue by markusmauch** [digaus/esphome-components-eqiva#21]
When adding
```
external_components:
  source: github://digaus/esphome-components-eqiva
  # use refresh when you do not get latest version
  # refresh: 0s

eqiva_key_ble:
  id: key_ble
```
to the esphome config yaml, the firmware builds and is uploaded to the ESP32-PICO-D4 but is is not available, neither over the air nor via USB connection.
Building the very same config to a ESP32 WROVER board works great, however...
