### ISSUE TITLE
More visiblity in Home Assistant

### ISSUE THREAD

**Issue by FredFoo** [digaus/esphome-components-eqiva#26]
I have done some changes to the original template that allows me to show more information on the lovelace card I am using. I am not sure if this is the best way, so far it works :)

The goal here is to split up the MOVING state and let HA know if the lock is currently opening or closing, in addition to be locked, unlocked or jammed.

```
# First, define a global variable to store the previous state
globals:
  - id: previous_lock_state
    type: std::string
    restore_value: true
    initial_value: '"UNKNOWN"'

# Lock component for HA, can also create two locks and use connect service to connect/control two different locks
# One ESP per lock is still recommended
lock:
  - platform: template
    name: "Lock_Main_Door"
    lambda: |-
      // Store current state in a local variable
      std::string current_state = id(lock_status).state;

      // State logic
      if (current_state == "LOCKED") {
        // Update previous state before returning
        id(previous_lock_state) = current_state;
        return LOCK_STATE_LOCKED;
      } else if (current_state == "UNLOCKED" || current_state == "OPENED") {
        // Update previous state before returning
        id(previous_lock_state) = current_state;
        return LOCK_STATE_UNLOCKED;
      } else if(current_state == "MOVING") {
        // Check previous state to determine if locking or unlocking
        if (id(previous_lock_state) == "LOCKED") {
          return LOCK_STATE_UNLOCKING;
        } else if (id(previous_lock_state) == "UNLOCKED" || id(previous_lock_state) == "OPENED") {
          return LOCK_STATE_LOCKING;
        } else {
          // Default case if previous state was UNKNOWN or MOVING
          return LOCK_STATE_LOCKING;
        }
      } else if (current_state == "UNKNOWN") {
        // Update previous state before returning
        id(previous_lock_state) = current_state;
        return LOCK_STATE_JAMMED;
      } 

      // Default fallback
      id(previous_lock_state) = current_state;
      return LOCK_STATE_LOCKED;

    lock_action:
      - eqiva_key_ble.lock:
    unlock_action:
      - eqiva_key_ble.unlock:
    open_action:    
      - eqiva_key_ble.open:
```

I also use the custom button card for the lock. This definition can display more states and also will show a red icon when the battries in the lock are low. Additionally, if the BLE connection is not established the card will have a white border. 

```
type: custom:button-card
name: Front Door
entity: lock.lock_main_door
size: 50px
layout: icon_state_name2nd
color: auto
color_type: card
tap_action:
  action: toggle
hold_action:
  action: more-info
show_state: true
state:
  - color: green
    value: locked
  - color: red
    value: unlocked
  - color: blue
    value: jammed
  - color: darkorange
    value: unlocking
  - color: yellow
    value: locking
styles:
  card:
    - border-width: 5px
    - border-color: |
        [[[ 
          if (states['sensor.lock_ble_state_2'].state != 'ESTABLISHED') 
          return 'white';
        ]]]
  icon:
    - color: >
        [[[ if (states['sensor.low_battery_2'].state == 'true') return 'red';
        ]]]

```
