### ISSUE TITLE
Help request: Disconnect BLE when API client not connected

### ISSUE THREAD

**Issue by user45876** [digaus/esphome-components-eqiva#9]
Dear digaus,

thank you so much for this. I was using a Zero 2 with several keyble for years and while it is great, this is looking to be more reliable and easier in the end. This has so much less moving parts than a zero with Node on it ;)

Hoowever, I am having two questiong and want to ask for help:
- it seems to stay connected forever despite me removing the 4 minute timer from the example. While this makes it instand, could you say what would need to be set to have it disconnect after some time?
- more importantly, you are having a condition, that it must be connected to wifi to start BLE scanning. How would I need to set it up to have it only scan when an API connection is established to HA? There is a condition api.connected (https://esphome.io/components/api) - but could you maybe put this into the example?

Thank you so much for your efforts, very much appreciated!
Corwin

**Comment by user45876** [comment]
After reading and trying to think in this bedlam I came up with this. Should this work? Is it enough or too much?
Desired behaviour is that it disconnects from the lock when the API is disconnected for whatever reason so the app can be used.

```
api:
  encryption:
    key: "..."

  on_client_connected:
    - esp32_ble_tracker.start_scan  # Start BLE scanning
    - eqiva_key_ble.connect:
       mac_address: !lambda 'return id(mac_address).state;' 
       user_id: !lambda 'return id(user_id).state;'
       user_key: !lambda 'return id(user_key).state;'

  on_client_disconnected:
    - if:
        condition:
          - not: api.connected
        then:
          - esp32_ble_tracker.stop_scan
          - eqiva_key_ble.disconnect 
```
